### ISSUE TITLE
[翻译挑战]-10010-Blockchain security

### ISSUE THREAD

**Issue by Oaciqihz** [decert-me/document#14]
- 挑战标题：Blockchain security
- 官网链接：https://decert.me/quests/10010
- 翻译文件：[/translation/en/10010.json](https://github.com/decert-me/document/blob/main/translation/en/10010.json)
- 目标文件：/translation/cn/10010.json ( 待创建 )

**Comment by deanplus** [comment]
认领翻译

**Comment by deanplus** [comment]
已翻译，PR #27

**Comment by deanplus** [comment]
校对完毕
