### ISSUE TITLE
[翻译合集]-6-Chainbase 链上数据训练营

### ISSUE THREAD

**Issue by Oaciqihz** [decert-me/document#30]
- 挑战标题：Chainbase 链上数据训练营
- 官网链接：https://decert.me/collection/6
- 翻译文件：[/translation/cn/collection_6.json](https://github.com/decert-me/document/blob/main/translation/cn/collection_6.json)
- 目标文件：/translation/en/collection_6.json ( 待创建 )

**Comment by deanplus** [comment]
认领

**Comment by deanplus** [comment]
已校对
